#!/bin/sh

apt-get update
apt-get install build-essential libssl-dev
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
command -v nvm
nvm install 10
nvm use 10
cd ~
wget 
