#!/bin/sh

apt-get update
apt-get install build-essential libssl-dev git
wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
command -v nvm
nvm install 10
nvm use 10
npm i -g pm2
cd ~
sudo adduser masterserver
sudo mkdir /masterserver
sudo chown masterserver /masterserver
cd ..
cd masterserver
git clone https://github.com/SaltyPandaStudios/Master-Server.git
sudo -u masterserver -c "pm2 start index.js"
